import{a as i,i as d}from"./assets/vendor-6d0036ef.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const u="https://api.thecatapi.com/v1",p="live_5by06OFwHheRUp9VstzvBimzl4BKirSYssLaw602WJRBzfwsIyF76sXRpAIxqc7F";i.defaults.headers.common["x-api-key"]=p;const l=i.create({baseURL:u});function f(){return l.get("/breeds")}function m(t){return l.get("images/search",{params:{breed_ids:t}})}const s={select:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),error:document.querySelector(".error"),catInfo:document.querySelector(".cat-info")};s.error.style.display="none";s.select.addEventListener("change",y);f().then(({data:t})=>{s.select.insertAdjacentHTML("beforeend",h(t))}).catch(t=>{d.error({title:"Error",message:`Oops! Something went wrong! Try reloading the page! ${t}`,timeout:2e3,position:topCenter})}).finally(()=>{s.loader.style.display="none"});function h(t){return console.log("DATA >>>",t),t.map(({id:o,name:n})=>`<option value=${o}>${n}</option>`).join("")}function y(t){const o=t.target.value;m(o).then(n=>g(n)).catch(n=>console.log(n))}function g(t){const{name:o,description:n,temperament:c}=t.data[0].breeds[0],{url:e}=t.data[0],r=`<div class="wrapper-card">
      <img class="image-cat" src="${e}" alt="${o}" width="600" />
      <div class="wrapper-info">
        <h2 class="name-cat">${o}</h2>
        <p class="description-cat">${n}</p>
        <p class="temperament-cat"><b>Temperament:</b> ${c}</p>
      </div>
    </div>`;s.catInfo.innerHTML=r}
//# sourceMappingURL=commonHelpers.js.map
