import{a as d,i as u,S as p}from"./assets/vendor-02fbc5f1.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const f="https://api.thecatapi.com/v1",m="live_5by06OFwHheRUp9VstzvBimzl4BKirSYssLaw602WJRBzfwsIyF76sXRpAIxqc7F",i=d.create({baseURL:f,headers:{common:{"x-api-key":m}}});function y(){return i.get("/breeds")}function h(r){return i.get("images/search",{params:{breed_ids:r,order:"ASC"}})}function g(){u.error({title:"ERROR",message:"Oops! Something went wrong! Try reloading the page!",timeout:3e3,position:"topCenter"})}const s={select:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),error:document.querySelector(".error"),catInfo:document.querySelector(".cat-info")},l="choose a cat",S=new p({select:s.select});s.select.addEventListener("change",L);y().then(({data:r})=>{s.select.innerHTML=b(r)}).catch(r=>{g(),s.error.style.display="block"}).finally(()=>{s.loader.style.display="none",s.error.style.display="none"});function b(r){const o=r.map(({id:n,name:c})=>({text:c,value:n}));return S.setData([{placeholder:!0,text:l},...o])}function L(r){s.catInfo.innerHTML="",s.loader.style.display="block";const o=r.target.value;o!==l&&h(o).then(n=>{const c=n.data[0];v({breeds:c.breeds[0],url:c.url})}).catch(n=>console.log(n)).finally(()=>s.loader.style.display="none")}function v({breeds:r,url:o}){const{name:n,description:c,temperament:e}=r,t=`<div class="wrapper-card">
      <img class="image-cat" src="${o}" alt="${n}" width="600" />
      <div class="wrapper-info">
        <h2 class="name-cat">${n}</h2>
        <p class="description-cat">${c}</p>
        <p class="temperament-cat"><b>Temperament:</b> ${e}</p>
      </div>
    </div>`;s.catInfo.innerHTML=t}
//# sourceMappingURL=commonHelpers.js.map
