import{a as u,i as p,S as f}from"./assets/vendor-02fbc5f1.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&c(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const m="https://api.thecatapi.com/v1",y="live_5by06OFwHheRUp9VstzvBimzl4BKirSYssLaw602WJRBzfwsIyF76sXRpAIxqc7F",i=u.create({baseURL:m,headers:{common:{"x-api-key":y}}});function h(){return i.get("/breeds")}function g(r){return i.get("images/search",{params:{breed_ids:r,order:"ASC"}})}function l(){p.error({title:"ERROR",message:"Oops! Something went wrong! Try reloading the page!",timeout:3e3,position:"topCenter"})}const o={select:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),error:document.querySelector(".error"),catInfo:document.querySelector(".cat-info")},d="choose a cat",L=new f({select:o.select});o.select.addEventListener("change",b);h().then(({data:r})=>{o.select.innerHTML=S(r)}).catch(r=>{l(),o.error.style.display="block"}).finally(()=>{o.select.classList.toggle("visually-hidden"),o.loader.style.display="none",o.error.style.display="none"});function S(r){const s=r.map(({id:n,name:c})=>({text:c,value:n}));return L.setData([{placeholder:!0,text:d},...s])}function b(r){o.catInfo.innerHTML="",o.loader.style.display="block";const s=r.target.value;s!==d&&g(s).then(n=>{const c=n.data[0];v({breeds:c.breeds[0],url:c.url})}).catch(n=>l()).finally(()=>o.loader.style.display="none")}function v({breeds:r,url:s}){const{name:n,description:c,temperament:e}=r,t=`<div class="wrapper-card">
      <img class="image-cat" src="${s}" alt="${n}" width="600" />
      <div class="wrapper-info">
        <h2 class="name-cat">${n}</h2>
        <p class="description-cat">${c}</p>
        <p class="temperament-cat"><b>Temperament:</b> ${e}</p>
      </div>
    </div>`;o.catInfo.innerHTML=t}
//# sourceMappingURL=commonHelpers.js.map
